### ISSUE TITLE
Errors & output missing for tests with RP 0.23 on stampede for lsdmap/gromacs 

### ISSUE THREAD

**Issue by ashkurti** [radical-cybertools/ExTASY#131]
The ExTASY log at: https://gist.github.com/ashkurti/7bd57dafc1195d7db17d

In addition to errors similar to Issue #128, I am afraid, I do not see any files that have been created on Stampede and then transferred at the end in the local machine: 

```
[ExTASY-tools] ardita@poirot 143% ls -al
total 1480
drwxr-xr-x   2 ardita pa    4096 Dec 16 13:28 .
drwxr-xr-x 182 ardita pa   12288 Dec 16 13:28 ..
-rw-r--r--   1 ardita pa       0 Dec 16 13:24 1
-rw-r--r--   1 ardita pa     264 Dec 15 14:52 config.ini
-rwxr-xr-x   1 ardita pa     165 Dec 15 14:52 extasy_grlsd.sh
-rw-r--r--   1 ardita pa  387459 Dec 16 13:27 extasy.log
-rw-r--r--   1 ardita pa    2235 Dec 15 14:52 gromacslsdmap.wcfg
-rw-r--r--   1 ardita pa     759 Dec 16 13:24 gromacslsdmap.wcfgc
-rw-r--r--   1 ardita pa    1409 Dec 15 14:52 grompp.mdp
-rw-r--r--   1 ardita pa 1072000 Dec 15 14:52 input.gro
-rw-r--r--   1 ardita pa     679 Dec 15 14:51 stampede.rcfg
-rw-r--r--   1 ardita pa     410 Dec 16 13:24 stampede.rcfgc
-rw-r--r--   1 ardita pa    6674 Dec 15 14:52 topol.top

```

**Comment by ashkurti** [comment]
@vivek-bala, @jp43 I still have problems, even after launching the test using Vivek's stampede account from the testing account in the notts workstations.

With the new release of extasy after clearing out and reinstalling everything using the master branch, I get the following version of extasy:
```
[ExTASY-tools] ardita@poirot 252% python -c 'import radical.ensemblemd.extasy as extasy; print extasy.version'
0.1-rc5-38-g37ae320
```

Repeating the gromacs/lsdmap workflow test with the new installation, there is a failure again, and no back-up folder is created at all. The extasy.log is at: https://gist.github.com/ashkurti/fe3c907ce0982b747f1a

**Comment by jp43** [comment]
Hi @ashkurti could you please check the file STDERR in the last unit-* folder created (you can find the most recent folder for example by using "ls -ltr"). This folder should be related to LSDMap and should also contain a file called lsdmap.log. Could you also print the contents of this file, thank you.

**Comment by ashkurti** [comment]
@jp43 please find below what I think you suggested me to check... let me know whether you need anything else ...

```
login3.stampede(24)$ pwd
/work/02998/ardi/radical.pilot.sandbox/pilot-54aa650ef8cdba20c5c2da49/unit-54aa65d1f8cdba20c5c2da5d
login3.stampede(25)$ ls
lsdmap  post_analyze.py  radical_pilot_cu_launch_script-_WenMs.sh  reweighting.py  select.py  STDERR  STDOUT  tmp.gro

```

and the STDERR content (I did not find any STDERR folder at all):

```

login3.stampede(23)$ more STDERR 
ln: accessing `/work/02998/ardi/radical.pilot.sandbox/pilot-54aa650ef8cdba20c5c2da49/unit-54aa65c9f8cdba20c5c2da5c/neighbors.nn': No such file or directory
ln: accessing `/work/02998/ardi/radical.pilot.sandbox/pilot-54aa650ef8cdba20c5c2da49/unit-54aa65c9f8cdba20c5c2da5c/tmpha.ev': No such file or directory
Traceback (most recent call last):
  File "select.py", line 98, in <module>
    SelectionStep().run()
  File "select.py", line 41, in run
    evfile = reader.open(args.evfile)
  File "/work/02998/ardi/radical.pilot.sandbox/pilot-54aa650ef8cdba20c5c2da49/unit-54aa65d1f8cdba20c5c2da5d/lsdmap/rw/reader.py", line 88, in open
    return known_formats[format].open(filename, kwargs)
  File "/work/02998/ardi/radical.pilot.sandbox/pilot-54aa650ef8cdba20c5c2da49/unit-54aa65d1f8cdba20c5c2da5d/lsdmap/rw/reader.py", line 45, in open
    return ev.Reader(filename, **kwargs)
  File "/work/02998/ardi/radical.pilot.sandbox/pilot-54aa650ef8cdba20c5c2da49/unit-54aa65d1f8cdba20c5c2da5d/lsdmap/rw/sl.py", line 16, in __init__
    self.file = open(self.filename, 'r')
IOError: [Errno 2] No such file or directory: 'tmpha.ev'
Traceback (most recent call last):
  File "reweighting.py", line 214, in <module>
    ReweightingStep().run()
  File "reweighting.py", line 134, in run
    self.initialize(args)
  File "reweighting.py", line 28, in initialize
    ncfile = reader.open(args.ncfile)
  File "/work/02998/ardi/radical.pilot.sandbox/pilot-54aa650ef8cdba20c5c2da49/unit-54aa65d1f8cdba20c5c2da5d/lsdmap/rw/reader.py", line 88, in open
    return known_formats[format].open(filename, kwargs)
  File "/work/02998/ardi/radical.pilot.sandbox/pilot-54aa650ef8cdba20c5c2da49/unit-54aa65d1f8cdba20c5c2da5d/lsdmap/rw/reader.py", line 37, in open
    return sl.Reader(filename, **kwargs)
  File "/work/02998/ardi/radical.pilot.sandbox/pilot-54aa650ef8cdba20c5c2da49/unit-54aa65d1f8cdba20c5c2da5d/lsdmap/rw/sl.py", line 16, in __init__
    self.file = open(self.filename, 'r')
IOError: [Errno 2] No such file or directory: 'ncopies.nc'
mv: cannot stat `out.gro': No such file or directory
ln: accessing `weight.w': No such file or directory
ln: accessing `1_input.gro': No such file or director
```

**Comment by vivek-bala** [comment]
Jordane has made the appropriate changes for the installation on Stampede. Tested extasy/master from the nottingham machine on to Stampede. Please test again.

**Comment by ashkurti** [comment]
Ok, I have retried, now the situation seems to be better. 
A backup folder is created containing information only on iter2, which I guess is right since there is a total of 3 num_iterations that we require.

```
[ExTASY-tools] ardita@poirot 368% ls -l *
-rw-r--r-- 1 ardita pa       0 Jan  5 18:10 1
-rw-r--r-- 1 ardita pa     264 Jan  5 18:10 config.ini
-rwxr-xr-x 1 ardita pa     165 Jan  5 18:10 extasy_grlsd.sh
-rw-r--r-- 1 ardita pa  673753 Jan  5 18:20 extasy.log
-rw-r--r-- 1 ardita pa    2235 Jan  5 18:10 gromacslsdmap.wcfg
-rw-r--r-- 1 ardita pa     759 Jan  5 18:10 gromacslsdmap.wcfgc
-rw-r--r-- 1 ardita pa    1409 Jan  5 18:10 grompp.mdp
-rw-r--r-- 1 ardita pa 1072000 Jan  5 18:10 input.gro
-rw-r--r-- 1 ardita pa     300 Jan  5 18:20 paths.txt
-rw-r--r-- 1 ardita pa     679 Jan  5 18:10 stampede.rcfg
-rw-r--r-- 1 ardita pa     410 Jan  5 18:10 stampede.rcfgc
-rw-r--r-- 1 ardita pa    6674 Jan  5 18:10 topol.top

backup:
total 4
drwxr-xr-x 2 ardita pa 4096 Jan  5 18:17 iter2

[ExTASY-tools] ardita@poirot 369% ls backup/iter2/
2_input.gro  lsdmap.log  weight.w
```

I still get some errors, I suppose "those" messages printed out as errors, but not sure whether we still need to ignore them.

New extasy log at: https://gist.github.com/ashkurti/e9ec27e782942a1590be
