### ISSUE TITLE
Gromas/LSDMap ExTASY 0.2 fails on Stampede

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/ExTASY#209]
the GRLSD workflow is also failing on Stampede, but with a different error to issue 208.  Here is the log:

```
(extasy-test)[ibethune@workflow grlsd-on-stampede]$ EXTASY_DEBUG=True RADICAL_ENMD_VERBOSE=REPORT python extasy_gromacs_lsdmap.py --RPconfig stampede.rcfg --Kconfig gromacslsdmap.wcfg

================================================================================
 EnsembleMD (0.3.6)                                                             
================================================================================

Starting Allocation                                                           ok
        Verifying pattern                                                     ok
        Starting pattern execution                                            ok
--------------------------------------------------------------------------------
Executing simulation-analysis loop with 1 iterations on 16 allocated core(s) on 'xsede.stampede'

Job waiting on queue...
Job is now running !
Waiting for pre_loop step to complete.                                      done
Iteration 1: Waiting for simulation tasks: md.gromacs to complete           done
Iteration 1: Waiting for analysis tasks: md.pre_lsdmap to complete2015-10-21 18:17:40,421: radical.enmd.simulation_analysis_loop.static.default: MainProcess                     : Thread-3       : ERROR   : ComputeUnit error: STDERR: [... CONTENT SHORTENED ...]
formation.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx trjconv, VERSION 5.0.6
Executable:   /opt/apps/intel15/mvapich2_2_1/gromacs/5.0.6/x86_64/bin/gmx
Library dir:  /opt/apps/intel15/mvapich2_2_1/gromacs/5.0.6/x86_64/share/gromacs/top
Command line:
  trjconv -f tmp.gro -s tmp.gro -o tmpha.gro

Will write gro: Coordinate file in Gromos-87 format

-------------------------------------------------------
Program trjconv, VERSION 5.0.6
Source code file: /home1/02875/micbuild/rpms/BUILD/gromacs-5.0.6/src/gromacs/fileio/confio.c, line: 906

Fatal error:
gro file does not have the number of atoms on the second line
For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors
-------------------------------------------------------

, STDOUT: [... CONTENT SHORTENED ...]
formation.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx trjconv, VERSION 5.0.6
Executable:   /opt/apps/intel15/mvapich2_2_1/gromacs/5.0.6/x86_64/bin/gmx
Library dir:  /opt/apps/intel15/mvapich2_2_1/gromacs/5.0.6/x86_64/share/gromacs/top
Command line:
  trjconv -f tmp.gro -s tmp.gro -o tmpha.gro

Will write gro: Coordinate file in Gromos-87 format

-------------------------------------------------------
Program trjconv, VERSION 5.0.6
Source code file: /home1/02875/micbuild/rpms/BUILD/gromacs-5.0.6/src/gromacs/fileio/confio.c, line: 906

Fatal error:
gro file does not have the number of atoms on the second line
For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors
-------------------------------------------------------


2015-10-21 18:17:40,421: radical.enmd.simulation_analysis_loop.static.default: MainProcess                     : Thread-3       : ERROR   : Pattern execution FAILED.
2015-10-21 18:17:40,422: radical.pilot       : MainProcess                     : Thread-3       : ERROR   : unit manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "/home/ibethune/extasy-test/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 261, in run
    self.call_unit_state_callbacks(unit_id, new_state)
  File "/home/ibethune/extasy-test/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 198, in call_unit_state_callbacks
    cb(self._shared_data[unit_id]['facade_object'], new_state)
  File "/home/ibethune/extasy-test/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/simulation_analysis_loop/static.py", line 141, in unit_state_cb
    sys.exit(1)
SystemExit: 1
Execution interuptedTraceback (most recent call last):
  File "/home/ibethune/extasy-test/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/simulation_analysis_loop/static.py", line 741, in execute_pattern
    resource._umgr.wait_units()
  File "/home/ibethune/extasy-test/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 697, in wait_units
    time.sleep (0.5)
KeyboardInterrupt

        Starting Deallocation                                               done
```

It appears that the file file tmp.gro which is read by trjconv has zero size.  Here are contents of the unit directory:

```
login2.stampede(11)$ pwd
/work/03283/tg825819/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.ibethune.016729.0023-pilot.0000/unit.000017
login2.stampede(12)$ ls -ltr
total 76
lrwxrwxrwx 1 tg825819 G-801782  134 Oct 21 17:17 pre_analyze.py -> /work/03283/tg825819/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.ibethune.016729.0023-pilot.0000/unit.000000/pre_analyze.py
lrwxrwxrwx 1 tg825819 G-801782  127 Oct 21 17:17 out9.gro -> /work/03283/tg825819/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.ibethune.016729.0023-pilot.0000/unit.000010/out.gro
lrwxrwxrwx 1 tg825819 G-801782  127 Oct 21 17:17 out8.gro -> /work/03283/tg825819/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.ibethune.016729.0023-pilot.0000/unit.000009/out.gro
lrwxrwxrwx 1 tg825819 G-801782  127 Oct 21 17:17 out7.gro -> /work/03283/tg825819/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.ibethune.016729.0023-pilot.0000/unit.000008/out.gro
lrwxrwxrwx 1 tg825819 G-801782  127 Oct 21 17:17 out6.gro -> /work/03283/tg825819/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.ibethune.016729.0023-pilot.0000/unit.000007/out.gro
lrwxrwxrwx 1 tg825819 G-801782  127 Oct 21 17:17 out5.gro -> /work/03283/tg825819/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.ibethune.016729.0023-pilot.0000/unit.000006/out.gro
lrwxrwxrwx 1 tg825819 G-801782  127 Oct 21 17:17 out4.gro -> /work/03283/tg825819/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.ibethune.016729.0023-pilot.0000/unit.000005/out.gro
lrwxrwxrwx 1 tg825819 G-801782  127 Oct 21 17:17 out3.gro -> /work/03283/tg825819/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.ibethune.016729.0023-pilot.0000/unit.000004/out.gro
lrwxrwxrwx 1 tg825819 G-801782  127 Oct 21 17:17 out2.gro -> /work/03283/tg825819/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.ibethune.016729.0023-pilot.0000/unit.000003/out.gro
lrwxrwxrwx 1 tg825819 G-801782  127 Oct 21 17:17 out1.gro -> /work/03283/tg825819/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.ibethune.016729.0023-pilot.0000/unit.000002/out.gro
lrwxrwxrwx 1 tg825819 G-801782  127 Oct 21 17:17 out15.gro -> /work/03283/tg825819/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.ibethune.016729.0023-pilot.0000/unit.000016/out.gro
lrwxrwxrwx 1 tg825819 G-801782  127 Oct 21 17:17 out14.gro -> /work/03283/tg825819/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.ibethune.016729.0023-pilot.0000/unit.000015/out.gro
lrwxrwxrwx 1 tg825819 G-801782  127 Oct 21 17:17 out13.gro -> /work/03283/tg825819/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.ibethune.016729.0023-pilot.0000/unit.000014/out.gro
lrwxrwxrwx 1 tg825819 G-801782  127 Oct 21 17:17 out12.gro -> /work/03283/tg825819/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.ibethune.016729.0023-pilot.0000/unit.000013/out.gro
lrwxrwxrwx 1 tg825819 G-801782  127 Oct 21 17:17 out11.gro -> /work/03283/tg825819/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.ibethune.016729.0023-pilot.0000/unit.000012/out.gro
lrwxrwxrwx 1 tg825819 G-801782  127 Oct 21 17:17 out10.gro -> /work/03283/tg825819/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.ibethune.016729.0023-pilot.0000/unit.000011/out.gro
lrwxrwxrwx 1 tg825819 G-801782  127 Oct 21 17:17 out0.gro -> /work/03283/tg825819/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.ibethune.016729.0023-pilot.0000/unit.000001/out.gro
-rw------- 1 tg825819 G-801782    0 Oct 21 17:17 STDOUT
-rwx------ 1 tg825819 G-801782  685 Oct 21 17:17 radical_pilot_cu_launch_script.sh
-rw------- 1 tg825819 G-801782    0 Oct 21 17:17 tmp.gro
-rw------- 1 tg825819 G-801782 2219 Oct 21 17:17 STDERR
login2.stampede(13)$ 
```

The root cause appears to be that the gromacs MD CUs did not produce any output because the environment was not set up correctly to run GROMACS:

```

The following have been reloaded with a version change:
  1) intel/15.0.2 => intel/13.0.2.146  2) mvapich2/2.1 => mvapich2/1.9a2


The following have been reloaded with a version change:
  1) intel/13.0.2.146 => intel/15.0.2  2) mvapich2/1.9a2 => mvapich2/2.1

Lmod has detected the following error: Cannot load module "gromacs/5.0.6"
without these module(s) loaded:
   cxx11


While processing the following module(s):

Module fullname  Module Filename
---------------  ---------------
gromacs/5.0.6    /opt/apps/intel15/mvapich2_2_1/modulefiles/gromacs/5.0.6.lua
run.sh: line 22: grompp: command not found
run.sh: line 23: mdrun: command not found
cat: confout.gro: No such file or directory
```

Looks like a missing module dependency???

**Comment by marksantcroos** [comment]
Dont know on which layer this needs to be solved, but to get gromacs going an additional "module load cxx11" should fix it. (afaik this was fixed on the ensemblemd layer)

**Comment by vivek-bala** [comment]
Added in enmd master.

**Comment by ibethune** [comment]
Confirm working with master!
