### ISSUE TITLE
ensemblemd devel: 'module' object has no attribute 'CANCELLED'

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/ExTASY#214]
Running the latest ensemblemd from devel I get an error:

```
(extasy-test)localhost:coam-on-archer ibethune$ RADICAL_ENMD_VERBOSE=Report RADICAL_VERBOSE=Report python extasy_amber_coco.py --RPconfig archer.rcfg --Kconfig cocoamber.wcfg 

================================================================================
 EnsembleMD (0.3.6-58-gbe17616)                                                 
================================================================================

Starting Allocation                                                            \
create session rp.session.Iains-MBP.home.ibethune.016738.0001                 ok
create pilot manager                                                          ok
create pilot description                                                      ok
submit 1 pilot(s) 2015-10-30 10:42:09,885: radical.pilot       : MainProcess                     : MainThread     : ERROR   : Couldn't call callback function 'module' object has no attribute 'CANCELLED'
Traceback (most recent call last):
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 258, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 134, in pilot_state_cb
    if state == radical.pilot.CANCELLED:
AttributeError: 'module' object has no attribute 'CANCELLED'
2015-10-30 10:42:09,886: radical.enmd.SingleClusterEnvironment: MainProcess                     : MainThread     : ERROR   : Fatal error during resource allocation: 'module' object has no attribute 'CANCELLED'.
Traceback (most recent call last):
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 193, in allocate
    self._pilot = pmgr.submit_pilots(pdesc)
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 356, in submit_pilots
    pilot.register_callback(self._default_pilot_state_cb)
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 389, in register_callback
    self._worker.register_pilot_callback(self, cb_func, cb_data)
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 481, in register_pilot_callback
    self._shared_data[pilot_uid]["data"]["state"]
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 258, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 134, in pilot_state_cb
    if state == radical.pilot.CANCELLED:
AttributeError: 'module' object has no attribute 'CANCELLED'
Allocation failed: 'module' object has no attribute 'CANCELLED'
        closing session rp.session.Iains-MBP.home.ibethune.016738.0001         \
close pilot manager -2015-10-30 10:42:11,380: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : Couldn't call callback function 'module' object has no attribute 'CANCELLED'
Traceback (most recent call last):
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 258, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 134, in pilot_state_cb
    if state == radical.pilot.CANCELLED:
AttributeError: 'module' object has no attribute 'CANCELLED'
\Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 335, in run
    self.call_callbacks(pilot_id, new_state)
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 258, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 134, in pilot_state_cb
    if state == radical.pilot.CANCELLED:
AttributeError: 'module' object has no attribute 'CANCELLED'

                                                           \
wait for 1 pilot(s) *                                                         ok
                                                                              ok
session lifetime: 6.9s                                                        ok
Traceback (most recent call last):
  File "extasy_amber_coco.py", line 191, in <module>
    cluster.allocate()
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 193, in allocate
    self._pilot = pmgr.submit_pilots(pdesc)
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 356, in submit_pilots
    pilot.register_callback(self._default_pilot_state_cb)
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 389, in register_callback
    self._worker.register_pilot_callback(self, cb_func, cb_data)
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 481, in register_pilot_callback
    self._shared_data[pilot_uid]["data"]["state"]
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 258, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 134, in pilot_state_cb
    if state == radical.pilot.CANCELLED:
AttributeError: 'module' object has no attribute 'CANCELLED'
```

**Comment by vivek-bala** [comment]
fixed in devel. It should be 'CANCELED'.

**Comment by ibethune** [comment]
Working now, thanks!
