### ISSUE TITLE
Python errors in LSDMap CU

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/ExTASY#226]
Using the lastest enmd from master, I get errors from the md.lsdmap analysis task:

```
python extasy_gromacs_lsdmap.py --RPconfig archer.rcfg --Kconfig gromacslsdmap.wcfg
...
Waiting for pre_loop step to complete.                                      done
Iteration 1: Waiting for simulation tasks: md.gromacs to complete           done
Iteration 1: Waiting for analysis tasks: md.pre_lsdmap to complete          done
Iteration 1: Waiting for analysis tasks: md.lsdmap to complete2015-12-17 14:37:58,524: radical.enmd.simulation_analysis_loop.static.default: MainProcess                     : Thread-3       : ERROR   : ComputeUnit error: STDERR: [... CONTENT SHORTENED ...]
umber of dimensionsall the input arrays must have same number of dimensions
return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)

ValueError: all the input arrays must have same number of dimensions
    self.coords = np.vstack(comm.allgather(coords_thread))
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
ValueError: all the input arrays must have same number of dimensions
ValueError: all the input arrays must have same number of dimensions
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
ValueError: all the input arrays must have same number of dimensions
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: all the input arrays must have same number of dimensions
, STDOUT: [... CONTENT SHORTENED ...]
umber of dimensionsall the input arrays must have same number of dimensions
return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)

ValueError: all the input arrays must have same number of dimensions
    self.coords = np.vstack(comm.allgather(coords_thread))
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
ValueError: all the input arrays must have same number of dimensions
ValueError: all the input arrays must have same number of dimensions
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
ValueError: all the input arrays must have same number of dimensions
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: all the input arrays must have same number of dimensions

2015-12-17 14:37:58,524: radical.enmd.simulation_analysis_loop.static.default: MainProcess                     : Thread-3       : ERROR   : Pattern execution FAILED.
2015-12-17 14:37:58,525: radical.pilot       : MainProcess                     : Thread-3       : ERROR   : unit manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 261, in run
    self.call_unit_state_callbacks(unit_id, new_state)
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 198, in call_unit_state_callbacks
    cb(self._shared_data[unit_id]['facade_object'], new_state)
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/simulation_analysis_loop/static.py", line 141, in unit_state_cb
    sys.exit(1)
SystemExit: 1
Execution interuptedTraceback (most recent call last):
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/simulation_analysis_loop/static.py", line 746, in execute_pattern
    resource._umgr.wait_units(uids)
  File "/Users/ibethune/Desktop/extasy-test/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 697, in wait_units
    time.sleep (0.5)
KeyboardInterrupt

        Starting Deallocation
Resource allocation cancelled.                                              done 
```

unit.000010/STDERR:

```
Traceback (most recent call last):
  File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
Traceback (most recent call last):
      File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
lsdm.LSDMap().run()
Traceback (most recent call last):
  File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
    Traceback (most recent call last):
lsdm.LSDMap().run()
Traceback (most recent call last):
  File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
  File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
Traceback (most recent call last):
      File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
Traceback (most recent call last):
lsdm.LSDMap().run()
Traceback (most recent call last):
        lsdm.LSDMap().run()
  File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
  File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
lsdm.LSDMap().run()
Traceback (most recent call last):
Traceback (most recent call last):
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
  File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
      File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
lsdm.LSDMap().run()
  File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
    lsdm.LSDMap().run()
      File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
lsdm.LSDMap().run()
  File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
Traceback (most recent call last):
      File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
  File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
lsdm.LSDMap().run()
Traceback (most recent call last):
    Traceback (most recent call last):
  File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
Traceback (most recent call last):
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
lsdm.LSDMap().run()
  File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
      File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
Traceback (most recent call last):
lsdm.LSDMap().run()
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
Traceback (most recent call last):
  File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
      File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
Traceback (most recent call last):
    lsdm.LSDMap().run()
lsdm.LSDMap().run()
  File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
  File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
    Traceback (most recent call last):
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
Traceback (most recent call last):
          File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
lsdm.LSDMap().run()
lsdm.LSDMap().run()
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
      File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
  File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
lsdm.LSDMap().run()
Traceback (most recent call last):
  File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
      File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
lsdm.LSDMap().run()
          File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
lsdm.LSDMap().run()
      File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
lsdm.LSDMap().run()
lsdm.LSDMap().run()
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
      File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
lsdm.LSDMap().run()
Traceback (most recent call last):
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
  File "/var//opt/cray/alps/spool/19440164/lsdmap", line 5, in <module>
      File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
lsdm.LSDMap().run()
lsdm.LSDMap().run()
    lsdm.LSDMap().run()
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 305, in run
        self.initialize(comm, config, args)
    self.initialize(comm, config, args)
self.initialize(comm, config, args)
            self.initialize(comm, config, args)
self.initialize(comm, config, args)
self.initialize(comm, config, args)
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
    self.initialize(comm, config, args)
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
        self.initialize(comm, config, args)
self.initialize(comm, config, args)
      File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
      File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
self.initialize(comm, config, args)
self.initialize(comm, config, args)
    self.initialize(comm, config, args)
            self.initialize(comm, config, args)
self.initialize(comm, config, args)
self.initialize(comm, config, args)
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
        self.initialize(comm, config, args)
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
        self.initialize(comm, config, args)
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
self.initialize(comm, config, args)
        self.initialize(comm, config, args)
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
self.initialize(comm, config, args)
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
        self.initialize(comm, config, args)
self.initialize(comm, config, args)
self.initialize(comm, config, args)
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
      File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
self.initialize(comm, config, args)
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
  File "/work/y07/y07/cse/lsdmap/lib/python2.7/site-packages/lsdmap/lsdm.py", line 34, in initialize
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: all the input arrays must have same number of dimensions
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
    ValueErrorreturn _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
:     ValueError    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
: ValueErrorall the input arrays must have same number of dimensionsall the input arrays must have same number of dimensions

: ValueErrorValueErrorall the input arrays must have same number of dimensions: : 
all the input arrays must have same number of dimensions    all the input arrays must have same number of dimensions
return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)

ValueError: all the input arrays must have same number of dimensions
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
    self.coords = np.vstack(comm.allgather(coords_thread))
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
    ValueErrorreturn _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: ValueError: all the input arrays must have same number of dimensions: 
ValueErrorValueErrorValueError: all the input arrays must have same number of dimensions: : all the input arrays must have same number of dimensions    all the input arrays must have same number of dimensions

all the input arrays must have same number of dimensionsreturn _nx.concatenate([atleast_2d(_m) for _m in tup], 0)


        return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError    all the input arrays must have same number of dimensions: ValueErrorreturn _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
: 
all the input arrays must have same number of dimensions
all the input arrays must have same number of dimensionsValueError    ValueErrorreturn _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
: : 
all the input arrays must have same number of dimensionsall the input arrays must have same number of dimensions
ValueError
    ValueError: : return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
    all the input arrays must have same number of dimensionsall the input arrays must have same number of dimensions
return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)

ValueError: all the input arrays must have same number of dimensions
    self.coords = np.vstack(comm.allgather(coords_thread))
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
ValueError: all the input arrays must have same number of dimensions
ValueError: all the input arrays must have same number of dimensions
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
    self.coords = np.vstack(comm.allgather(coords_thread))
  File "/work/y07/y07/cse/numpy/1.9.2-libsci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
ValueError: all the input arrays must have same number of dimensions
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: all the input arrays must have same number of dimensions
```

Let me know if any further info is needed to help debugging...

**Comment by vivek-bala** [comment]
Could you check if you have the file "tmpha.gro" in the lsdmap folder ?

**Comment by ibethune** [comment]
Yes, it exists, but it contains only 23 structures
 ```
e290ib@eslogin007:/work/e290/e290/e290ib/radical.pilot.sandbox/rp.session.mbp-ib.epcc.ed.ac.uk.ibethune.016786.0008-pilot.0000/unit.000010> ls -l
total 36
lrwxrwxrwx 1 e290ib e290   131 Dec 17 15:44 config.ini -> /work/e290/e290/e290ib/radical.pilot.sandbox/rp.session.mbp-ib.epcc.ed.ac.uk.ibethune.016786.0008-pilot.0000/unit.000000/config.ini
-rw------- 1 e290ib e290    42 Dec 17 15:45 lsdmap.log
-rwx------ 1 e290ib e290   859 Dec 17 15:44 radical_pilot_cu_launch_script.sh
-rw------- 1 e290ib e290 16248 Dec 17 15:45 STDERR
-rw------- 1 e290ib e290   134 Dec 17 15:45 STDOUT
lrwxrwxrwx 1 e290ib e290   130 Dec 17 15:44 tmpha.gro -> /work/e290/e290/e290ib/radical.pilot.sandbox/rp.session.mbp-ib.epcc.ed.ac.uk.ibethune.016786.0008-pilot.0000/unit.000000/tmpha.gro
e290ib@eslogin007:/work/e290/e290/e290ib/radical.pilot.sandbox/rp.session.mbp-ib.epcc.ed.ac.uk.ibethune.016786.0008-pilot.0000/unit.000010> ls -l /work/e290/e290/e290ib/radical.pilot.sandbox/rp.session.mbp-ib.epcc.ed.ac.uk.ibethune.016786.0008-pilot.0000/unit.000000/tmpha.gro
-rw------- 1 e290ib e290 17733 Dec 17 15:44 /work/e290/e290/e290ib/radical.pilot.sandbox/rp.session.mbp-ib.epcc.ed.ac.uk.ibethune.016786.0008-pilot.0000/unit.000000/tmpha.gro
```

**Comment by ibethune** [comment]
Hi Vivek, sorry but I can confirm this is still an issue for me - happy to help with the debug if you tell me what to look for.

**Comment by ebreitmo** [comment]
I encountered this error sometimes, but not all of the time...

**Comment by vivek-bala** [comment]
#238 needs to be fixed before this.

**Comment by ibethune** [comment]
This seems to be the same as #240 so no need to keep this one open.
