### ISSUE TITLE
Module loading issues: Error in initializing MVAPICH2 ptmalloc library

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/ExTASY#87]
```

Inactive Modules:
  1) gromacs

The following have been reloaded with a version change:
  1) intel/13.0.2.146 => intel/14.0.1.106  2) mvapich2/1.9a2 => mvapich2/2.0b


The following have been reloaded with a version change:
  1) python/2.7.3-epd-7.3.2 => python/2.7.6

WARNING: Error in initializing MVAPICH2 ptmalloc library.Continuing without InfiniBand registration cache support.
Traceback (most recent call last):
  File "/home1/02734/vivek91/lsdmap/bin/lsdmap", line 5, in <module>
    lsdm.LSDMap().run()
  File "/home1/02734/vivek91/.local/lib/python2.7/site-packages/lsdmap/lsdm.py", line 370, in run
    self.save_nneighbors(comm, args, DistanceMatrix, epsilon_thread)
  File "/home1/02734/vivek91/.local/lib/python2.7/site-packages/lsdmap/lsdm.py", line 239, in save_nneighbors
    neighbor_matrix = comm.recv(source=idx, tag=1000+idx)
  File "Comm.pyx", line 816, in mpi4py.MPI.Comm.recv (src/mpi4py.MPI.c:72032)
  File "pickled.pxi", line 250, in mpi4py.MPI.PyMPI_recv (src/mpi4py.MPI.c:29545)
  File "pickled.pxi", line 111, in mpi4py.MPI._p_Pickle.load (src/mpi4py.MPI.c:28058)
EOFError
[c463-103.stampede.tacc.utexas.edu:mpirun_rsh][signal_processor] Caught signal 15, killing job

```

**Comment by samcom12** [comment]
@vivek-bala  Hello,

May I know how you fixed it?
We are also getting same error at our end.

Cheers,
Samir Shaikh

**Comment by andre-merzky** [comment]
hi @samcom12 - that ticket is quite a blast from the past! :-P  

If my memory served correctly, the problem was resolved by TACC staff providing a new `mpi4py` deployment.  I do not know what was changed in that deployment, and I doubt that knowledge can be recovered at this point.
